[workspace]
resolver = "2"
members = [
    # Core infrastructure
    "crates/shared/protocol",

    
    # Node applications
    "crates/nodes/phantom",
    
    # Standalone tools
    "crates/tools/dns_signer",
    
    # Plugins
    "crates/nodes/edge",
]

[profile.release]
strip = true
opt-level = 3
