[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-L", "native=/Users/zvwgvx/Antigravity/phantom-mesh/vendor/npcap-sdk/Lib/x64"]

[target.x86_64-unknown-linux-musl]
linker = "/Users/zvwgvx/Antigravity/phantom-mesh/zig-cc"
rustflags = ["-C", "link-self-contained=no", "-C", "link-arg=-target", "-C", "link-arg=x86_64-linux-musl"]

[target.aarch64-unknown-linux-musl]
linker = "/Users/zvwgvx/Antigravity/phantom-mesh/zig-cc"
rustflags = ["-C", "link-self-contained=no", "-C", "link-arg=-target", "-C", "link-arg=aarch64-linux-musl"]

